# Generated by Django 4.1 on 2023-06-27 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0006_auto_20200808_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='room_type',
        ),
    ]
