# Generated by Django 4.1 on 2023-06-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0007_remove_rooms_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='size',
        ),
    ]
